version: '3.8'

services:
  api:
    build: .
    container_name: flight_api
    ports:
      - "8000:8000"
    networks:
      - test_network
    env_file:
      - .env

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test    
    container_name: test_container
    networks:
      - test_network
    command: sh test_api.sh
    depends_on:
      - api

networks:
  test_network: